---
title: "EWAS Long Island Effect"
author: "Marie-Laurence Cossette"
date: "23/07/2022"
output:
  html_document: default
  pdf_document: default
---

https://rpubs.com/mlcossette9224/948888

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load required packages

```{r Load package, echo=TRUE, message=FALSE, warning=FALSE}
#load packages
library("limma")
library("dplyr")
library("lattice")
library("ggplot2")
library("tidyr")

#set working directory
setwd("~/Desktop/SCHOOL/THESIS/Chapter 2 - Methyl/PAPER/Gitlab uploads/")
```

### 1. Load data with info for all samples and the methylation probe data

```{r Load data, echo=TRUE, results='hide'}
#load data on shrew
df <- read.csv("SampleSheetAgeN90final.csv")
#subset samples to only use ones that can be used for ageing (basically remove ones that didn't pass QC)
samples <- subset(df, CanBeUsedForAgingStudies == 'yes') 
#look at structure of data frame
str(df)

#load probe data
load("all_probes_sesame_normalized.Rdata")
#match the probe data with your samples info
data <- normalized_betas_sesame %>% tibble::column_to_rownames(var = "CGid")%>%
  dplyr::select(samples$Basename)
#look at structure of data frame
str(data)

#load my mapped probes
probe_marie_cinereusshrewn90 <- read.csv("aln_2.csv")

### Data refinement of CpG Sites, based on shared probe mappings
#add new column called "qname" to be able to match CGids with probe data set 
data_1<- cbind(qname = rownames(data), data)
#subset columns that have matching CGids (removes about 8 thousand cols)
data_2 <- subset(data_1, qname %in% probe_marie_cinereusshrewn90$qname)
#remove that new column because we need only numeric values in table for matrix step coming up in a bit
data <- data_2[ -c(1)]

#remove fetus from "df" dataset
df_nofet=subset(df, df$Age>0.1)
#remove fetus from "data" based on the "df" dataframe
data_nofet <- subset(data, select = df$Age>0.1)
#remove BPI shrews from both data sets
df_LI= subset(df_nofet, df_nofet$Location != "Bon Portage Island Nova Scotia")
data_LI <- subset(data_nofet, select = df_nofet$Location != "Bon Portage Island Nova Scotia")
#add new "Location_1" column to separate Long Island samples from all others ("yes" = from Long Island)
df_LI<- mutate(df_LI, Location_1 = ifelse(df_LI$Location == "Long Island Nova Scotia", "yes", "no"))  
```

### 2. EWAS of island effect

Code inspired by <https://rstudio-pubs-static.s3.amazonaws.com/13450_cca08b93a0d94bc2b45c9ed94e230d02.html>

```{r matrix, echo=TRUE, message=FALSE, results='hide'}
#make matrix with variables to be able to run EWAS
#I want my model to include sex, age, tissue type and Long Island/others location
(df_LIMat <- model.matrix(~Location_1 + Age + Sex + Tissue, df_LI))
```

```{r correlation, echo=TRUE, message=FALSE, warning=FALSE, results='hide'}
#Estimate the correlation between samples from same individual to be able to include and account for it in regression model
cor <- duplicateCorrelation(data_LI, df_LIMat, block=df_LI$AnimalID)
cor$consensus.correlation
```

```{r EWAS, echo=TRUE, message=FALSE}
#use limma package to run regressions
#need probe dataset (data_LI), matrix with sample info (df_LI), and info on duplicate correlation from above
Fit <- lmFit(data_LI, df_LIMat, block = df_LI$AnimalID, correlation = cor$consensus.correlation)
#use eBayes() to moderate the estimated error variances
EbFit <- eBayes(Fit)
#add "CGid" column based on rownames
EbFit$CGid <- rownames(EbFit)
#view info on top significant CpGs
topTable(EbFit)

#save output to computer
write.csv(EbFit, file="~/Desktop/SCHOOL/THESIS/Chapter 2 - Methyl/PAPER/Gitlab uploads/EWAS/EbFit_LongIsland_effect.csv")
```

```{r coefficients, echo=TRUE, message=FALSE}
#view data for each variable/coefficient (outputs in order of most significant)
#Location
coeff_2 <- topTable(EbFit,coef=2)
CpG_2 <- rownames(coeff_2)
coeff_2
#Age
coeff_3 <- topTable(EbFit,coef=3)
CpG_3 <- rownames(coeff_3)
coeff_3
#Sex
coeff_4 <-topTable(EbFit,coef=4)
CpG_4 <- rownames(coeff_4)
coeff_4
```

```{r data fix, echo=TRUE}
#Re-arrange data for plotting
#make matrix
data_LI_M <- as.matrix(data_LI)
#transpose data (basically swap rows and columns to have CGid as column and sample ID as rows)
data_LI_M <- t(data_LI_M)
#add new column at the start for Basename (copying the actual rownames and making a column out of it)
data_LI_M <- cbind(Basename = rownames(data_LI_M), data_LI_M)
#change back to dataframe
data_LI_M <- as.data.frame(data_LI_M)
#bind the re-arranged probe data with the sample data frame (df_LI) using the "Basename" column
allData <- cbind(df_LI, Basename = data_LI_M)
```

### 3. Plotting significant CpGs

#### 1. Linear regression of DNAm level vs age for top 10 significant CpGs

```{r plotting linear regression for age, echo=TRUE, warning=FALSE, message=FALSE}
#put CpGs of interest (top 10) in the same column using gather (change wide format to tall)
allData_long <- gather(allData, CPG, Value, Basename.cg00059486, Basename.cg19873240, Basename.cg03886239, Basename.cg03789886, Basename.cg02898094, Basename.cg26301436, Basename.cg15647667, Basename.cg08938156, Basename.cg13753818, Basename.cg15944967, factor_key=TRUE)
#change CpG methylation value to numeric
allData_long$Value <- as.numeric(allData_long$Value)
#plot linear regression of DNAm level vs age for top 10 significant CpGs
baseplot <- ggplot(allData_long, aes(allData_long$Age, allData_long$Value, color=allData_long$CPG)) + geom_point(size = 1)
#add title and axis labels
baseplot <- baseplot + ggtitle("CpG methylation over age") + xlab("Age (years)") + ylab("DNAm level")
#make each CpG have a unique color and change legend names
baseplot <- baseplot + scale_colour_discrete(name="CpG", breaks=c("Basename.cg00059486", "Basename.cg19873240", "Basename.cg03886239", "Basename.cg03789886", "Basename.cg02898094", "Basename.cg26301436", "Basename.cg15647667", "Basename.cg08938156", "Basename.cg13753818", "Basename.cg15944967"), labels=c("cg00059486", "cg19873240", "cg03886239", "cg03789886", "cg02898094", "cg26301436", "cg15647667", "cg08938156", "cg13753818", "cg15944967"))
#add regression line
DNAm_Age_plot <- baseplot + geom_smooth(method = "lm") 
#view plot
DNAm_Age_plot
```

#### 2. Boxplots DNAm level vs location for top 10 significant CpGs

```{r plotting boxplots for location, echo=TRUE, warning=FALSE, message=FALSE, fig.dim = c(10, 6)}
#need to update and put CpGs of interest (top 10)in the same column using gather (change wide format to tall)
allData_long_2 <- gather(allData, CPG_2, Value_2, Basename.cg01463565, Basename.cg13695149, Basename.cg09711113, Basename.cg09227150, Basename.cg11703808, Basename.cg17205049, Basename.cg12694663, Basename.cg22063749, Basename.cg20521676, Basename.cg00152260, factor_key=TRUE)
#change CpG methylation value to numeric
allData_long_2$Value_2 <- as.numeric(allData_long_2$Value_2)
##change CpG names for legend, got the info on specific genes from Manhattan plot scripts
allData_long_2$CPG_2 <- factor(allData_long_2$CPG_2, levels = c("Basename.cg01463565", "Basename.cg13695149", "Basename.cg09711113", "Basename.cg09227150", "Basename.cg11703808", "Basename.cg17205049", "Basename.cg12694663", "Basename.cg22063749", "Basename.cg20521676", "Basename.cg00152260"), 
labels = c("cg01463565 NET1_Promoter", "cg13695149 NET1_Promoter", "cg09711113 TM256_Promoter", "cg09227150", "cg11703808 EWS_Exon", "cg17205049", "cg12694663", "cg22063749 UBP54_Intron", "cg20521676 PARVA_Exon", "cg00152260 PO4F3_Intron"))

library(ggrepel)
#plot boxplots of DNAm level vs location for top 10 significant CpGs 
DNAm_Location_plot <- ggplot(allData_long_2, aes(x=allData_long_2$CPG_2, allData_long_2$Value_2, fill=allData_long_2$Location_1)) +
  geom_boxplot() + 
  #put boxplot for each CpG in its own panel, each panel has its own range of values for the y axis, put 5 side by side per row and edit labeller to avoid cropped text
  facet_wrap(~allData_long_2$CPG_2, scale="free", ncol =5, labeller = label_wrap_gen(10)) +
  #change title and axis names
  ggtitle("CpG Methylation Levels") + xlab("") + ylab("DNAm Level") +
  #remove x axis labels
  scale_x_discrete(labels = NULL, breaks = NULL) + 
   #select colors (red and blue), specify legend labels
  scale_fill_manual(values=c("#fb6869", "#66b1ff"), name="Location", breaks=c("no", "yes"), labels=c("Other", "Long Island")) +
  #use classic theme
  theme_classic() +
  #select size for all of the text on the plot
  theme(plot.title = element_text(hjust = 0.5, size = 13, face="bold"),
        strip.text = element_text(size=11),
        axis.text = element_text(size =10),
        axis.title = element_text(size = 11),
        legend.title = element_text(size=11),
        legend.text = element_text(size=10))
#view plot
DNAm_Location_plot
```

#### 3. Boxplots DNAm level vs sex for top 10 significant CpGs

```{r plotting boxplots for sex, echo=TRUE, warning=FALSE, message=FALSE, fig.dim = c(10, 6)}
#need to update and put CpGs of interest (top 10) in the same column using gather (change wide format to tall)
allData_long_3 <- gather(allData, CPG_3, Value_3, Basename.cg10876267, Basename.cg21064897, Basename.cg13324140, Basename.cg04927657, Basename.cg13102615, Basename.cg11115577, Basename.cg15281901, Basename.cg13842554, Basename.cg01042193, Basename.cg07121495, factor_key=TRUE)
#change cpg methylation value to numeric
allData_long_3$Value_3 <- as.numeric(allData_long_3$Value_3)
#change CpG names for legend
allData_long_3$CPG_3 <- factor(allData_long_3$CPG_3, levels=c("Basename.cg10876267", "Basename.cg21064897", "Basename.cg13324140", "Basename.cg04927657", "Basename.cg13102615", "Basename.cg11115577", "Basename.cg15281901", "Basename.cg13842554", "Basename.cg01042193", "Basename.cg07121495"),labels = c("cg10876267", "cg21064897", "cg13324140", "cg04927657", "cg13102615", "cg11115577", "cg15281901", "cg13842554", "cg01042193", "cg07121495"))

#plot boxplots of DNAm level vs sex for top 10 significant CpGs
DNAm_Sex_plot <- ggplot(allData_long_3, aes(allData_long_3$CPG_3, allData_long_3$Value_3, fill=allData_long_3$Sex)) + 
  geom_boxplot() + 
  #put boxplot for each CpG in its own panel, each panel has its own range of values for the y axis and put 5 side by side per row
  facet_wrap(~allData_long_3$CPG_3, scale="free", ncol =5) +
  #change title and axis names
  ggtitle("CpG methylation by sex") + xlab("") + ylab("DNAm level") +
   #remove x axis labels
  scale_x_discrete(labels = NULL, breaks = NULL) + 
  #specification for color fill 
  labs(fill = "Sex") + 
  #select colors (red and blue)
  scale_fill_manual(values=c("#fb6869", "#66b1ff")) +
  #use theme classic
  theme_classic() +
  #select size for all of the text on the plot
  theme(plot.title = element_text(hjust = 0.5, size = 13, face="bold"),
        strip.text = element_text(size=11),
        axis.text = element_text(size =10),
        axis.title = element_text(size = 11),
        legend.title = element_text(size=11),
        legend.text = element_text(size=10))
#view plot
DNAm_Sex_plot
```
